runtime: go114
env: standard

handlers:
- url: /(.*)
  script: auto

- url: /assets/(.*)
  static_files: www/assets/\1
  upload: www/assets/(.*)

- url: /css/(.*)
  static_files: www/css/\1
  upload: www/css/(.*)


manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10