runtime: go114
env: standard

handlers:
- url: /assets/(.*)
  static_files: www/assets/\1
  upload: www/assets/.*\.(jpg|png)$

- url: /css
  static_dir: www/css

- url: /.*
  script: auto

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10